In [19]:
import numpy as np
import scipy

In [18]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

In [27]:
a*b

array([[ -6,   0, -35]])

In [32]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [33]:
np.array([2,3,4],[5,6,7],[8,9,0])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [35]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
np.arange(1, 13, 2).reshape((3, 2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [45]:
a = np.eye(4, 5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [52]:
a[[0, 3], [1,3]]

array([0., 1.])